// One question per day, cycling through the list — deterministic by date so
// everyone (eventually) sees the same prompt on the same day, and reloading
// the page never shows a different one.
// Each one is deliberately concrete — anchored to a specific person, moment,
// or thing rather than a pure abstract "what does X mean to you" question,
// which is easy to write but hard to actually sit down and answer.
const PROMPTS = [
  "Who's someone you're grateful to have in your life right now, and why?",
  "What's a small moment from the last few days that's stuck with you?",
  "What's something you've been avoiding — a task, a conversation, a decision?",
  "What's a compliment someone gave you that you still think about?",
  "What's one thing about your daily routine you'd change if you could?",
  "What's a worry that's been quietly sitting in the back of your mind?",
  "Describe a moment recently when you felt genuinely happy.",
  "What's something you did recently that you're proud of, even if no one noticed?",
  "Who's someone you'd like to reconnect with, and what's stopping you?",
  "What's a habit you have that you'd like to change?",
  "What's something you're looking forward to in the next few weeks?",
  "What's a decision you're currently putting off?",
  "What's a memory from when you were younger that still makes you smile?",
  "What's something you wish people understood about you?",
  "What's a place that makes you feel calm — when did you last go there?",
  "What's something you learned about yourself recently?",
  "What's a fear that's been holding you back lately?",
  "Who do you think of when you imagine being truly supported?",
  "What's something you've forgiven yourself for?",
  "What's a goal you have that you haven't told many people about?",
  "What's a boundary you've set, or want to set, with someone?",
  "What's something small that reliably improves your mood?",
  "What's a risk you've been thinking about taking?",
  "What's something you did today that felt genuinely like you?",
  "What's a piece of advice you'd give your younger self?",
  "What's a conversation you keep replaying in your head?",
  "What's something you're better at now than you were a year ago?",
  "What's a story from your life you like telling people?",
  "What's something you need to let go of?",
  "Who's someone that's shaped who you are, and how?",
  "Is there a comparison you make with someone else that isn't helping you?",
  "What's something you're currently curious about learning or trying?",
  "What does feeling properly rested actually look like for you?",
  "What's a compliment you'd give yourself right now, honestly?",
  "What's a pattern you keep noticing in how you react to things?",
  "What's something you did today purely for yourself?",
  "What's a question you wish someone would ask you more often?",
  "What's a belief about yourself you've outgrown?",
  "What's something you're excited about that you haven't told anyone yet?",
  "What's a small win from today that's easy to overlook?",
  "What's something you own that you'd be genuinely upset to lose?",
  "Who's someone you don't say thank you to enough?",
  "What's a rule you live by that most people don't know you have?",
  "What's something that annoyed you today, and is it actually worth the energy?",
  "What's a skill you're proud of that has nothing to do with work or school?",
  "What's something you said recently that you wish you could take back?",
  "What's a smell, song, or taste that instantly takes you somewhere else?",
  "What's something you're doing differently this year than last?",
  "Who's the last person who made you laugh properly, and what happened?",
  "What's a piece of your routine that nobody else knows about?",
  "What's something you're stubborn about that maybe you shouldn't be?",
  "What's a version of yourself from a few years ago you'd like to check in on?",
  "What's something you've gotten better at accepting?",
  "What's a text or message you've been meaning to send?",
  "What's something you do that makes you feel like an adult, even if you don't feel ready?",
  "What's a place you've never been that you think about often?",
  "What's something you're quietly competitive about?",
  "What's a mistake you made that taught you something you needed?",
  "Who's someone you look up to, and what specifically do you admire about them?",
  "What's something you did today that you'd do again tomorrow without thinking?",
  "What's a question about your future you don't have an answer to yet?",
  "What's something you've been putting off buying, doing, or trying — and why?",
  "What's a way you've changed your mind about something recently?",
  "What's something that made today different from an ordinary day?",
  "What's a compliment you find hard to accept, even when you know it's true?",
  "What's something you're doing purely out of habit that you should question?",
  "What's a memory connected to a specific piece of music?",
  "What's something you wish you'd started sooner?",
  "What's a way you show people you care, that they might not notice?",
  "What's something that's easier for you now than it used to be?",
  "What's a conversation you've been avoiding having with yourself?",
  "What's something you did today that no one asked you to do?",
  "What's a rule someone taught you growing up that you still follow?",
  "What's something you're trying to prove, and who are you trying to prove it to?",
  "What's a moment today where you had to choose between two versions of yourself?",
  "What's something you've stopped apologising for?",
  "What's a small thing someone did for you recently that you haven't properly thanked them for?",
  "What's something you're doing right now that your younger self would be amazed by?",
  "What's a thought you had today that you didn't say out loud?",
  "What's something you're better at explaining than actually doing?",
  "What's a moment recently when you felt completely present, not thinking about anything else?",
  "What's something about the last week that surprised you?",
  "What's a way you've grown that only people close to you would notice?",
  "What's something you're holding onto hope about?",
  "What's a small act of kindness you witnessed or received recently?",
  "What's something you do when no one's watching that says something about who you are?",
  "What's a question you'd ask your future self, five years from now?",
  "What's something you did today that took more courage than it looked like?",
  "What's a lesson you keep having to relearn?",
  "What's something about today you'll have forgotten by next week — and is that okay?",
];

// Day-of-year in the same UTC sense used everywhere else in this app
// (dates are stored as midnight UTC calendar days).
function dayOfYear(dateISO: string): number {
  const date = new Date(`${dateISO}T00:00:00.000Z`);
  const startOfYear = new Date(Date.UTC(date.getUTCFullYear(), 0, 1));
  return Math.floor((date.getTime() - startOfYear.getTime()) / 86_400_000);
}

export function promptForDate(dateISO: string): string {
  return PROMPTS[dayOfYear(dateISO) % PROMPTS.length];
}
