// One question per day, cycling through the list — deterministic by date so
// everyone (eventually) sees the same prompt on the same day, and reloading
// the page never shows a different one.
// Each one is deliberately concrete — anchored to a specific person, moment,
// or thing rather than a pure abstract "what does X mean to you" question,
// which is easy to write but hard to actually sit down and answer.
const PROMPTS = [
  "Who's someone you're grateful to have in your life right now, and why?",
  "What's a small moment from the last few days that's stuck with you?",
  "What's something you've been avoiding — a task, a conversation, a decision?",
  "What's a compliment someone gave you that you still think about?",
  "What's one thing about your daily routine you'd change if you could?",
  "What's a worry that's been quietly sitting in the back of your mind?",
  "Describe a moment recently when you felt genuinely happy.",
  "What's something you did recently that you're proud of, even if no one noticed?",
  "Who's someone you'd like to reconnect with, and what's stopping you?",
  "What's a habit you have that you'd like to change?",
  "What's something you're looking forward to in the next few weeks?",
  "What's a decision you're currently putting off?",
  "What's a memory from when you were younger that still makes you smile?",
  "What's something you wish people understood about you?",
  "What's a place that makes you feel calm — when did you last go there?",
  "What's something you learned about yourself recently?",
  "What's a fear that's been holding you back lately?",
  "Who do you think of when you imagine being truly supported?",
  "What's something you've forgiven yourself for?",
  "What's a goal you have that you haven't told many people about?",
  "What's a boundary you've set, or want to set, with someone?",
  "What's something small that reliably improves your mood?",
  "What's a risk you've been thinking about taking?",
  "What's something you did today that felt genuinely like you?",
  "What's a piece of advice you'd give your younger self?",
  "What's a conversation you keep replaying in your head?",
  "What's something you're better at now than you were a year ago?",
  "What's a story from your life you like telling people?",
  "What's something you need to let go of?",
  "Who's someone that's shaped who you are, and how?",
  "Is there a comparison you make with someone else that isn't helping you?",
  "What's something you're currently curious about learning or trying?",
  "What does feeling properly rested actually look like for you?",
  "What's a compliment you'd give yourself right now, honestly?",
  "What's a pattern you keep noticing in how you react to things?",
  "What's something you did today purely for yourself?",
  "What's a question you wish someone would ask you more often?",
  "What's a belief about yourself you've outgrown?",
  "What's something you're excited about that you haven't told anyone yet?",
  "What's a small win from today that's easy to overlook?",
  "What's something you own that you'd be genuinely upset to lose?",
  "Who's someone you don't say thank you to enough?",
  "What's a rule you live by that most people don't know you have?",
  "What's something that annoyed you today, and is it actually worth the energy?",
  "What's a skill you're proud of that has nothing to do with work or school?",
  "What's something you said recently that you wish you could take back?",
  "What's a smell, song, or taste that instantly takes you somewhere else?",
  "What's something you're doing differently this year than last?",
  "Who's the last person who made you laugh properly, and what happened?",
  "What's a piece of your routine that nobody else knows about?",
  "What's something you're stubborn about that maybe you shouldn't be?",
  "What's a version of yourself from a few years ago you'd like to check in on?",
  "What's something you've gotten better at accepting?",
  "What's a text or message you've been meaning to send?",
  "What's something you do that makes you feel like an adult, even if you don't feel ready?",
  "What's a place you've never been that you think about often?",
  "What's something you're quietly competitive about?",
  "What's a mistake you made that taught you something you needed?",
  "Who's someone you look up to, and what specifically do you admire about them?",
  "What's something you did today that you'd do again tomorrow without thinking?",
  "What's a question about your future you don't have an answer to yet?",
  "What's something you've been putting off buying, doing, or trying — and why?",
  "What's a way you've changed your mind about something recently?",
  "What's something that made today different from an ordinary day?",
  "What's a compliment you find hard to accept, even when you know it's true?",
  "What's something you're doing purely out of habit that you should question?",
  "What's a memory connected to a specific piece of music?",
  "What's something you wish you'd started sooner?",
  "What's a way you show people you care, that they might not notice?",
  "What's something that's easier for you now than it used to be?",
  "What's a conversation you've been avoiding having with yourself?",
  "What's something you did today that no one asked you to do?",
  "What's a rule someone taught you growing up that you still follow?",
  "What's something you're trying to prove, and who are you trying to prove it to?",
  "What's a moment today where you had to choose between two versions of yourself?",
  "What's something you've stopped apologising for?",
  "What's a small thing someone did for you recently that you haven't properly thanked them for?",
  "What's something you're doing right now that your younger self would be amazed by?",
  "What's a thought you had today that you didn't say out loud?",
  "What's something you're better at explaining than actually doing?",
  "What's a moment recently when you felt completely present, not thinking about anything else?",
  "What's something about the last week that surprised you?",
  "What's a way you've grown that only people close to you would notice?",
  "What's something you're holding onto hope about?",
  "What's a small act of kindness you witnessed or received recently?",
  "What's something you do when no one's watching that says something about who you are?",
  "What's a question you'd ask your future self, five years from now?",
  "What's something you did today that took more courage than it looked like?",
  "What's a lesson you keep having to relearn?",
  "What's something about today you'll have forgotten by next week — and is that okay?",
  "What's a piece of clothing or object that reminds you of a specific person?",
  "What's something you're spending money on right now that isn't actually worth it to you?",
  "Who's someone you've lost touch with that you think about more than you'd expect?",
  "What's a household task you've been putting off, and what's the real reason?",
  "What's something about your body you've made peace with recently?",
  "What's a promise you made to yourself that you're still keeping?",
  "What's something you noticed about a stranger today?",
  "What's a way your environment (your room, your desk, your commute) affects your mood?",
  "What's something you used to be embarrassed about that doesn't bother you anymore?",
  "What's a decision from the past year you're glad you made?",
  "What's something you're doing to look after future-you?",
  "What's a piece of feedback that stung at the time but turned out to be right?",
  "What's something you do differently when you're alone versus around others?",
  "What's a goal you've quietly given up on, and are you actually okay with that?",
  "What's something you learned from someone younger than you?",
  "What's a time today you chose the harder but better option?",
  "What's something you're trying not to think about right now?",
  "What's a friendship that's changed shape over the years — for better or worse?",
  "What's something you do that you'd never admit to doing?",
  "What's a place in your home that feels the most like you?",
  "What's something you're weirdly sentimental about?",
  "What's a habit someone in your family has that you've picked up too?",
  "What's something you did today that you're going to be tired from tomorrow?",
  "What's a version of a plan you had that didn't happen — and what actually did instead?",
  "What's something you're better at than you give yourself credit for?",
  "What's a time recently you asked for help, or wish you had?",
  "What's something you've noticed change about how you spend your evenings?",
  "What's a text you got today that changed your mood, for better or worse?",
  "What's something you're doing to make peace with a part of your past?",
  "What's a piece of your identity you're still figuring out?",
  "What's something that felt like a big deal a year ago but doesn't anymore?",
  "What's a rule you break on purpose, and why?",
  "What's something you did today that felt like progress, even if small?",
  "What's a way you're different with your family than with your friends?",
  "What's something you're avoiding looking at directly — a bill, a message, a number?",
  "What's a compliment you gave someone today, or wish you had?",
  "What's something you're doing on autopilot that deserves more attention?",
  "What's a memory that gets better the more time passes?",
  "What's something you did today purely because it was expected of you?",
  "What's a skill you'd like to have that you've never actually tried to learn?",
  "What's something about your week that's felt out of your control?",
  "What's a small ritual you have that helps you start or end the day?",
  "What's something you're proud of that would surprise people who know you?",
  "What's a way you've supported someone else this week?",
  "What's something you keep meaning to throw away or get rid of, but haven't?",
  "What's a moment today that felt ordinary but you'll probably remember?",
  "What's something you're grieving, even if it's small — a plan, a version of yourself, a phase?",
  "What's a piece of advice you gave someone recently that you should probably take yourself?",
  "What's something that made you feel old today, in a good or bad way?",
  "What's a time you changed your plans for someone else, and how did it feel?",
  "What's something you're not very good at that you've stopped feeling bad about?",
  "What's a place you feel most like yourself in?",
  "What's something you did today that you'd want someone to notice, but probably didn't say?",
  "What's a value you hold that you don't talk about much?",
  "What's something you're looking at differently after today?",
  "What's a fear you had as a kid that seems strange to you now?",
  "What's something you're doing this week that's just for fun, with no other purpose?",
  "What's a way you comfort yourself when things go wrong?",
  "What's something you noticed you needed today, and did you give it to yourself?",
  "What's a conversation today that left you thinking afterward?",
  "What's something you've done recently that your past self couldn't have?",
  "What's a small disappointment from today that's worth naming, even if it's minor?",
  "What's something you're curious how other people experience differently than you?",
  "What's a piece of your morning or evening you'd protect if your schedule got busier?",
  "What's something you did today that took energy you didn't think you had?",
  "What's a way you've been kind to yourself this week?",
  "What's something you're avoiding changing, even though you know it'd help?",
  "What's a detail from today most people would miss, but you noticed?",
  "What's something you're quietly hoping happens soon?",
  "What's a way you've relied on someone else recently, and how did that feel?",
  "What's something about getting older that you're actually looking forward to?",
  "What's a moment today where you had more patience than usual?",
  "What's something you're doing that future-you will thank you for?",
  "What's a belief your family has that you don't share?",
  "What's something you did today that was harder than it needed to be, and why?",
  "What's a way you show up for people that costs you more than they realise?",
  "What's something small that went right today that you almost didn't notice?",
  "What's a habit you'd like someone close to you to pick up too?",
  "What's something you're pretending not to care about?",
  "What's a place from your childhood that still feels significant?",
  "What's something you did today that you'll tell someone about later?",
  "What's a way you've changed how you handle stress compared to a few years ago?",
  "What's something you wish took less effort than it does?",
  "What's a moment this week you felt closest to someone?",
  "What's something you're carrying that isn't actually yours to carry?",
  "What's a way today felt different from yesterday?",
  "What's something you did for the first time recently, even something small?",
  "What's a piece of your life right now you wouldn't have predicted a year ago?",
  "What's something you're trying to be more honest with yourself about?",
  "What's a way you take care of people without them asking?",
  "What's something that's been on your mind that you haven't said out loud to anyone?",
  "What's a small thing you did today that made someone else's day slightly better?",
  "What's something you're learning to sit with instead of fix?",
  "What's a moment today you almost didn't clock, but it mattered?",
  "What's something you're doing that's building toward a version of you that you actually want to be?",
  "What's a meal or food that instantly puts you in a better mood?",
  "What's something you've built, made, or fixed that you're quietly proud of?",
  "What's a way your phone habits have changed recently, for better or worse?",
  "What's something you learned today that you didn't expect to?",
  "What's a season of the year that suits you best, and why?",
  "What's something you'd do differently if you weren't worried what people thought?",
  "What's a way you've been patient with someone who tested it?",
  "What's something you're avoiding starting because the first step feels too big?",
  "What's a piece of music, book, or film that changed how you think about something?",
  "What's something you did today that was purely practical, with no meaning attached — and was that okay?",
  "What's a way you've noticed yourself becoming more like a parent or someone who raised you?",
  "What's something you're trying to unlearn?",
  "What's a moment today you felt behind, and is that feeling actually accurate?",
  "What's something you did today that you'll be glad you did in a week's time?",
  "What's a way you handle being wrong?",
  "What's something you're saving up for, financially or otherwise?",
  "What's a conversation you had today that you wish had gone differently?",
  "What's something about your current routine that you'd defend to someone who questioned it?",
  "What's a way you've shown resilience this week, even in something small?",
  "What's something you're quietly dreading?",
  "What's a place you go, physically or mentally, to reset?",
  "What's something you did today that you couldn't have done a year ago?",
  "What's a way you're different online than you are in person?",
  "What's something you're proud of that took longer than you expected?",
  "What's a boundary someone respected today that you were grateful for?",
  "What's something you noticed about how your energy changed throughout today?",
  "What's a piece of clutter — physical or mental — you'd like to clear out?",
  "What's something you did today that you almost talked yourself out of?",
  "What's a way you've made a hard week easier on yourself?",
  "What's something you're proud of your body for, regardless of how it looks?",
  "What's a moment today when you felt underestimated, or underestimated someone else?",
  "What's something you'd want to be remembered for, even in a small way?",
  "What's a risk that paid off, even a small one?",
  "What's something you're doing consistently that you haven't given yourself credit for?",
  "What's a way you've changed your relationship with rest?",
  "What's something you noticed a friend or family member needed today?",
  "What's a piece of your day that felt rushed, and what would slowing it down look like?",
  "What's something you're proud of that had nothing to do with achievement?",
  "What's a way you've had to compromise recently, and how did it sit with you?",
  "What's something you did today that you'd call an act of self-respect?",
  "What's a memory tied to a specific smell you can conjure instantly?",
  "What's something you're doing to stay connected to people who live far away?",
  "What's a way you've surprised yourself this month?",
  "What's something you did today that no one will ever know about?",
  "What's a piece of advice you've ignored, that you're starting to think you shouldn't have?",
  "What's something you're grateful your past self did, even if it was hard at the time?",
  "What's a way you'd like to be treated more often?",
  "What's something you did today that felt like a small act of bravery?",
  "What's a place you associate with a specific person?",
  "What's something you're doing today that's purely maintenance — keeping things okay, not moving forward — and is that enough for today?",
  "What's a way you've noticed your priorities shifting lately?",
  "What's something you did today that you'd want a friend to know you did?",
  "What's a mistake you're glad you made, in hindsight?",
  "What's something about tomorrow you're already thinking about?",
  "What's a way you've been generous with your time recently?",
  "What's something you're holding yourself to a stricter standard on than you'd hold anyone else?",
  "What's a piece of your week that felt lighter than expected?",
  "What's something you did today that reminded you of who you used to be?",
  "What's a way you comfort someone else that you rarely offer yourself?",
  "What's something small you're looking forward to tomorrow?",
  "What's a conversation you've been rehearsing in your head?",
  "What's something you did today that took discipline, even in a small way?",
  "What's a way this week has tested your patience, and how did you handle it?",
  "What's something you're glad is finally over, or almost over?",
  "What's a piece of good news, small or large, you got recently?",
  "What's something you did today that you'd call an act of care for someone else?",
  "What's a habit from someone you admire that you'd like to copy?",
  "What's something you're noticing about how you've handled a hard situation better than before?",
  "What's a place you feel unseen, and does that need to change?",
  "What's something you did today that felt like closing a loop?",
  "What's a way you've had to advocate for yourself recently?",
  "What's something you're quietly excited about, even if it seems small to others?",
  "What's a moment today you chose rest over pushing through, or pushing through over rest — and was it the right call?",
  "What's something you noticed change in a relationship recently, for better or worse?",
  "What's a way you've been more forgiving of yourself lately?",
  "What's something you did today that you've been meaning to do for a while?",
  "What's a piece of your identity that feels more solid than it used to?",
  "What's something you're trying to protect right now — your time, your energy, your peace?",
  "What's a moment today that made you feel useful?",
  "What's something you did today that you'd class as pure indulgence, guilt-free?",
  "What's a way you've noticed yourself setting a better example than you used to?",
  "What's something you're still figuring out about what makes you happy?",
  "What's a conversation you had today that felt easier than it used to be?",
  "What's something you did today that only future-you will understand the value of?",
];

// Day-of-year in the same UTC sense used everywhere else in this app
// (dates are stored as midnight UTC calendar days).
function dayOfYear(dateISO: string): number {
  const date = new Date(`${dateISO}T00:00:00.000Z`);
  const startOfYear = new Date(Date.UTC(date.getUTCFullYear(), 0, 1));
  return Math.floor((date.getTime() - startOfYear.getTime()) / 86_400_000);
}

export function promptForDate(dateISO: string): string {
  return PROMPTS[dayOfYear(dateISO) % PROMPTS.length];
}
