// The built-in exercise library shown on the Workout page (userId: null =
// everyone sees the same set). Grouped and named the way Hevy groups its
// own library — by specific muscle group rather than a broad push/pull
// split, with equipment variants spelled out (Barbell/Dumbbell/Cable/
// Machine/Smith Machine/Bodyweight) — since that's how people actually
// search for "the exercise I just did at the gym."
//
// Shared by prisma/seed.ts (fresh installs) and the one-off script that
// seeds/updates local + production directly (see scripts/ in git history
// around the exercise-library expansion commits).
export const EXERCISE_LIBRARY: { name: string; category: string }[] = [
  // Chest
  { name: "Barbell Bench Press", category: "Chest" },
  { name: "Incline Barbell Bench Press", category: "Chest" },
  { name: "Decline Barbell Bench Press", category: "Chest" },
  { name: "Close-Grip Barbell Bench Press", category: "Chest" },
  { name: "Dumbbell Bench Press", category: "Chest" },
  { name: "Incline Dumbbell Press", category: "Chest" },
  { name: "Decline Dumbbell Bench Press", category: "Chest" },
  { name: "Dumbbell Fly", category: "Chest" },
  { name: "Incline Dumbbell Fly", category: "Chest" },
  { name: "Decline Dumbbell Fly", category: "Chest" },
  { name: "Machine Chest Press", category: "Chest" },
  { name: "Incline Machine Chest Press", category: "Chest" },
  { name: "Smith Machine Bench Press", category: "Chest" },
  { name: "Smith Machine Incline Bench Press", category: "Chest" },
  { name: "Cable Fly", category: "Chest" },
  { name: "Low Cable Fly", category: "Chest" },
  { name: "High Cable Fly", category: "Chest" },
  { name: "Cable Crossover", category: "Chest" },
  { name: "Pec Deck", category: "Chest" },
  { name: "Push Up", category: "Chest" },
  { name: "Incline Push Up", category: "Chest" },
  { name: "Decline Push Up", category: "Chest" },
  { name: "Diamond Push Up", category: "Chest" },
  { name: "Chest Dip", category: "Chest" },
  { name: "Landmine Press", category: "Chest" },
  { name: "Svend Press", category: "Chest" },
  { name: "Guillotine Press", category: "Chest" },
  { name: "Single Arm Cable Press", category: "Chest" },

  // Back
  { name: "Deadlift", category: "Back" },
  { name: "Sumo Deadlift", category: "Back" },
  { name: "Deficit Deadlift", category: "Back" },
  { name: "Trap Bar Deadlift", category: "Back" },
  { name: "Rack Pull", category: "Back" },
  { name: "Barbell Row", category: "Back" },
  { name: "Pendlay Row", category: "Back" },
  { name: "T-Bar Row", category: "Back" },
  { name: "Chest Supported Row", category: "Back" },
  { name: "Seal Row", category: "Back" },
  { name: "Dumbbell Row", category: "Back" },
  { name: "Single Arm Dumbbell Row", category: "Back" },
  { name: "Kroc Row", category: "Back" },
  { name: "Seated Cable Row", category: "Back" },
  { name: "Wide Grip Seated Cable Row", category: "Back" },
  { name: "Close Grip Seated Cable Row", category: "Back" },
  { name: "Machine Row", category: "Back" },
  { name: "Lat Pulldown", category: "Back" },
  { name: "Wide-Grip Lat Pulldown", category: "Back" },
  { name: "Close-Grip Lat Pulldown", category: "Back" },
  { name: "Reverse-Grip Lat Pulldown", category: "Back" },
  { name: "Single Arm Lat Pulldown", category: "Back" },
  { name: "Straight Arm Pulldown", category: "Back" },
  { name: "Pull Up", category: "Back" },
  { name: "Chin Up", category: "Back" },
  { name: "Wide Grip Pull Up", category: "Back" },
  { name: "Neutral Grip Pull Up", category: "Back" },
  { name: "Assisted Pull Up", category: "Back" },
  { name: "Weighted Pull Up", category: "Back" },
  { name: "Barbell Shrug", category: "Back" },
  { name: "Dumbbell Shrug", category: "Back" },
  { name: "Machine Shrug", category: "Back" },
  { name: "Cable Shrug", category: "Back" },
  { name: "Back Extension", category: "Back" },
  { name: "Meadows Row", category: "Back" },
  { name: "Inverted Row", category: "Back" },
  { name: "Renegade Row", category: "Back" },

  // Shoulders
  { name: "Overhead Press", category: "Shoulders" },
  { name: "Seated Barbell Overhead Press", category: "Shoulders" },
  { name: "Behind the Neck Press", category: "Shoulders" },
  { name: "Push Press", category: "Shoulders" },
  { name: "Dumbbell Shoulder Press", category: "Shoulders" },
  { name: "Seated Dumbbell Shoulder Press", category: "Shoulders" },
  { name: "Arnold Press", category: "Shoulders" },
  { name: "Machine Shoulder Press", category: "Shoulders" },
  { name: "Smith Machine Shoulder Press", category: "Shoulders" },
  { name: "Lateral Raise", category: "Shoulders" },
  { name: "Cable Lateral Raise", category: "Shoulders" },
  { name: "Machine Lateral Raise", category: "Shoulders" },
  { name: "Leaning Lateral Raise", category: "Shoulders" },
  { name: "Front Raise", category: "Shoulders" },
  { name: "Cable Front Raise", category: "Shoulders" },
  { name: "Plate Front Raise", category: "Shoulders" },
  { name: "Rear Delt Fly", category: "Shoulders" },
  { name: "Cable Rear Delt Fly", category: "Shoulders" },
  { name: "Reverse Pec Deck", category: "Shoulders" },
  { name: "Face Pull", category: "Shoulders" },
  { name: "Upright Row", category: "Shoulders" },
  { name: "Cable Upright Row", category: "Shoulders" },
  { name: "Cuban Press", category: "Shoulders" },
  { name: "Egyptian Lateral Raise", category: "Shoulders" },
  { name: "Bus Driver", category: "Shoulders" },
  { name: "Viking Press", category: "Shoulders" },

  // Biceps
  { name: "Barbell Curl", category: "Biceps" },
  { name: "EZ-Bar Curl", category: "Biceps" },
  { name: "Reverse Barbell Curl", category: "Biceps" },
  { name: "Dumbbell Curl", category: "Biceps" },
  { name: "Alternating Dumbbell Curl", category: "Biceps" },
  { name: "Hammer Curl", category: "Biceps" },
  { name: "Cross-Body Hammer Curl", category: "Biceps" },
  { name: "Incline Dumbbell Curl", category: "Biceps" },
  { name: "Spider Curl", category: "Biceps" },
  { name: "Concentration Curl", category: "Biceps" },
  { name: "Zottman Curl", category: "Biceps" },
  { name: "Preacher Curl", category: "Biceps" },
  { name: "Dumbbell Preacher Curl", category: "Biceps" },
  { name: "Machine Preacher Curl", category: "Biceps" },
  { name: "Cable Curl", category: "Biceps" },
  { name: "Cable Hammer Curl", category: "Biceps" },
  { name: "Rope Cable Curl", category: "Biceps" },
  { name: "Machine Bicep Curl", category: "Biceps" },
  { name: "21s", category: "Biceps" },
  { name: "Drag Curl", category: "Biceps" },
  { name: "Waiter Curl", category: "Biceps" },
  { name: "Cable Preacher Curl", category: "Biceps" },

  // Triceps
  { name: "Tricep Pushdown", category: "Triceps" },
  { name: "Rope Tricep Pushdown", category: "Triceps" },
  { name: "V-Bar Tricep Pushdown", category: "Triceps" },
  { name: "Single Arm Tricep Pushdown", category: "Triceps" },
  { name: "Overhead Tricep Extension", category: "Triceps" },
  { name: "Dumbbell Overhead Tricep Extension", category: "Triceps" },
  { name: "Cable Overhead Tricep Extension", category: "Triceps" },
  { name: "Skull Crusher", category: "Triceps" },
  { name: "EZ-Bar Skull Crusher", category: "Triceps" },
  { name: "Dumbbell Skull Crusher", category: "Triceps" },
  { name: "Close-Grip Bench Press", category: "Triceps" },
  { name: "JM Press", category: "Triceps" },
  { name: "Tricep Dip", category: "Triceps" },
  { name: "Bench Dip", category: "Triceps" },
  { name: "Weighted Dip", category: "Triceps" },
  { name: "Tricep Kickback", category: "Triceps" },
  { name: "Cable Tricep Kickback", category: "Triceps" },
  { name: "Tate Press", category: "Triceps" },
  { name: "Diamond Bench Press", category: "Triceps" },

  // Forearms
  { name: "Wrist Curl", category: "Forearms" },
  { name: "Reverse Wrist Curl", category: "Forearms" },
  { name: "Reverse Curl", category: "Forearms" },
  { name: "Farmer's Carry", category: "Forearms" },
  { name: "Plate Pinch", category: "Forearms" },
  { name: "Dead Hang", category: "Forearms" },
  { name: "Behind the Back Wrist Curl", category: "Forearms" },
  { name: "Wrist Roller", category: "Forearms" },

  // Quadriceps
  { name: "Barbell Back Squat", category: "Quadriceps" },
  { name: "Barbell Front Squat", category: "Quadriceps" },
  { name: "Box Squat", category: "Quadriceps" },
  { name: "Pause Squat", category: "Quadriceps" },
  { name: "Goblet Squat", category: "Quadriceps" },
  { name: "Dumbbell Squat", category: "Quadriceps" },
  { name: "Smith Machine Squat", category: "Quadriceps" },
  { name: "Hack Squat", category: "Quadriceps" },
  { name: "Barbell Hack Squat", category: "Quadriceps" },
  { name: "Leg Press", category: "Quadriceps" },
  { name: "Single Leg Press", category: "Quadriceps" },
  { name: "Bulgarian Split Squat", category: "Quadriceps" },
  { name: "Dumbbell Split Squat", category: "Quadriceps" },
  { name: "Barbell Split Squat", category: "Quadriceps" },
  { name: "Walking Lunge", category: "Quadriceps" },
  { name: "Reverse Lunge", category: "Quadriceps" },
  { name: "Forward Lunge", category: "Quadriceps" },
  { name: "Lateral Lunge", category: "Quadriceps" },
  { name: "Dumbbell Lunge", category: "Quadriceps" },
  { name: "Step Up", category: "Quadriceps" },
  { name: "Leg Extension", category: "Quadriceps" },
  { name: "Sissy Squat", category: "Quadriceps" },
  { name: "Belt Squat", category: "Quadriceps" },
  { name: "Zercher Squat", category: "Quadriceps" },
  { name: "Spanish Squat", category: "Quadriceps" },
  { name: "Pistol Squat", category: "Quadriceps" },
  { name: "Sissy Squat Machine", category: "Quadriceps" },

  // Hamstrings
  { name: "Romanian Deadlift", category: "Hamstrings" },
  { name: "Dumbbell Romanian Deadlift", category: "Hamstrings" },
  { name: "Stiff-Leg Deadlift", category: "Hamstrings" },
  { name: "Good Morning", category: "Hamstrings" },
  { name: "Lying Leg Curl", category: "Hamstrings" },
  { name: "Seated Leg Curl", category: "Hamstrings" },
  { name: "Standing Leg Curl", category: "Hamstrings" },
  { name: "Nordic Curl", category: "Hamstrings" },
  { name: "Glute Ham Raise", category: "Hamstrings" },
  { name: "Swiss Ball Leg Curl", category: "Hamstrings" },
  { name: "Single Leg Romanian Deadlift", category: "Hamstrings" },

  // Calves
  { name: "Standing Calf Raise", category: "Calves" },
  { name: "Machine Standing Calf Raise", category: "Calves" },
  { name: "Seated Calf Raise", category: "Calves" },
  { name: "Leg Press Calf Raise", category: "Calves" },
  { name: "Donkey Calf Raise", category: "Calves" },

  // Glutes
  { name: "Hip Thrust", category: "Glutes" },
  { name: "Machine Hip Thrust", category: "Glutes" },
  { name: "Single Leg Hip Thrust", category: "Glutes" },
  { name: "Glute Bridge", category: "Glutes" },
  { name: "Cable Glute Kickback", category: "Glutes" },
  { name: "Machine Glute Kickback", category: "Glutes" },
  { name: "Sumo Squat", category: "Glutes" },
  { name: "Hip Abduction Machine", category: "Glutes" },
  { name: "Hip Adduction Machine", category: "Glutes" },
  { name: "Cable Pull Through", category: "Glutes" },

  // Abdominals
  { name: "Plank", category: "Abdominals" },
  { name: "Side Plank", category: "Abdominals" },
  { name: "Weighted Plank", category: "Abdominals" },
  { name: "Crunch", category: "Abdominals" },
  { name: "Bicycle Crunch", category: "Abdominals" },
  { name: "Cable Crunch", category: "Abdominals" },
  { name: "Machine Crunch", category: "Abdominals" },
  { name: "Reverse Crunch", category: "Abdominals" },
  { name: "Sit Up", category: "Abdominals" },
  { name: "Weighted Sit Up", category: "Abdominals" },
  { name: "Decline Sit Up", category: "Abdominals" },
  { name: "Hanging Leg Raise", category: "Abdominals" },
  { name: "Hanging Knee Raise", category: "Abdominals" },
  { name: "Captain's Chair Leg Raise", category: "Abdominals" },
  { name: "Russian Twist", category: "Abdominals" },
  { name: "Ab Wheel Rollout", category: "Abdominals" },
  { name: "Mountain Climber", category: "Abdominals" },
  { name: "V-Up", category: "Abdominals" },
  { name: "Toe Touch", category: "Abdominals" },
  { name: "Cable Woodchopper", category: "Abdominals" },
  { name: "Dead Bug", category: "Abdominals" },
  { name: "Flutter Kicks", category: "Abdominals" },
  { name: "Pallof Press", category: "Abdominals" },
  { name: "Hollow Body Hold", category: "Abdominals" },
  { name: "L-Sit", category: "Abdominals" },
  { name: "Stir the Pot", category: "Abdominals" },

  // Full Body & Olympic
  { name: "Clean", category: "Full Body & Olympic" },
  { name: "Power Clean", category: "Full Body & Olympic" },
  { name: "Hang Clean", category: "Full Body & Olympic" },
  { name: "Squat Clean", category: "Full Body & Olympic" },
  { name: "Snatch", category: "Full Body & Olympic" },
  { name: "Power Snatch", category: "Full Body & Olympic" },
  { name: "Hang Snatch", category: "Full Body & Olympic" },
  { name: "Clean and Jerk", category: "Full Body & Olympic" },
  { name: "Thruster", category: "Full Body & Olympic" },
  { name: "Suitcase Carry", category: "Full Body & Olympic" },
  { name: "Kettlebell Swing", category: "Full Body & Olympic" },
  { name: "Turkish Get-Up", category: "Full Body & Olympic" },
  { name: "Burpee", category: "Full Body & Olympic" },
  { name: "Wall Ball", category: "Full Body & Olympic" },
  { name: "Battle Ropes", category: "Full Body & Olympic" },
  { name: "Sled Push", category: "Full Body & Olympic" },
  { name: "Sled Pull", category: "Full Body & Olympic" },
  { name: "Box Jump", category: "Full Body & Olympic" },
  { name: "Man Maker", category: "Full Body & Olympic" },
  { name: "Farmer's Walk", category: "Full Body & Olympic" },
  { name: "Tire Flip", category: "Full Body & Olympic" },
  { name: "Bear Crawl", category: "Full Body & Olympic" },
  { name: "Sled Drag", category: "Full Body & Olympic" },
  { name: "Devil Press", category: "Full Body & Olympic" },
];
