-- AlterEnum
ALTER TYPE "Badge" ADD VALUE 'JOURNAL_STREAK_100';
ALTER TYPE "Badge" ADD VALUE 'STUDY_STREAK_30';
ALTER TYPE "Badge" ADD VALUE 'WORKOUT_STREAK_30';
ALTER TYPE "Badge" ADD VALUE 'LEVEL_20';
ALTER TYPE "Badge" ADD VALUE 'LEVEL_50';
ALTER TYPE "Badge" ADD VALUE 'TOTAL_WORKOUTS_10';
ALTER TYPE "Badge" ADD VALUE 'TOTAL_WORKOUTS_50';
ALTER TYPE "Badge" ADD VALUE 'TOTAL_WORKOUTS_100';
ALTER TYPE "Badge" ADD VALUE 'TOTAL_STUDY_HOURS_10';
ALTER TYPE "Badge" ADD VALUE 'TOTAL_STUDY_HOURS_50';
ALTER TYPE "Badge" ADD VALUE 'FIRST_FRIEND';
ALTER TYPE "Badge" ADD VALUE 'EARLY_BIRD';
ALTER TYPE "Badge" ADD VALUE 'NIGHT_OWL';

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "usernameChangedAt" TIMESTAMP(3);
